### ISSUE TITLE
跑一会儿直接未响应

### ISSUE THREAD

**Issue by Assassins-white** [qianxiao996/FrameScan-GUI#2]
![图片](https://user-images.githubusercontent.com/39295496/83369768-f3bd4480-a3ef-11ea-81d9-24a7e0fcfebb.png)

**Comment by Assassins-white** [comment]
sorry，更新到最新版解决了

**Comment by qianxiao996** [comment]
那个版本，我有两个循环写反了。所以会出现停止运行，后面就修复了。

**Comment by Assassins-white** [comment]
好，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qianxiao996"<notifications@github.com&gt;; 
发送时间: 2020年6月1日(星期一) 下午3:20
收件人: "qianxiao996/FrameScan-GUI"<FrameScan-GUI@noreply.github.com&gt;; 
抄送: "Assassins 小白"<assassins-white@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [qianxiao996/FrameScan-GUI] 跑一会儿直接未响应 (#2)





 
那个版本，我有两个循环写反了。所以会出现停止运行，后面就修复了。
