### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by cc8ci** [qianxiao996/FrameScan-GUI#3]
随手抓了3千个域名，放进去跑。
三次都跑一段时间跑着跑着突然进程结束。

**Comment by qianxiao996** [comment]
请问你是用的最新版吗？不是最新的话更新下版本，也有可能你放的域名太多了。或者线程太高了。域名特别多的话建议使用命令行版本。

**Comment by cc8ci** [comment]
是最新版本的。知道了，我有时间试下命令行版本
