### ISSUE TITLE
打包成exe后无法运行

### ISSUE THREAD

**Issue by littlebin404** [qianxiao996/FrameScan-GUI#5]
根据师傅的打包命令：
`pyinstaller -F FrameScan-GUI.py -i main.ico  --hidden-import eventlet.hubs.epolls --hidden-import eventlet.hubs.kqueue    --hidden-import  eventlet.hubs.selects --hidden-import dns --hidden-import dns.dnssec --hidden-import dns.e164  --hidden-import dns.hash  --hidden-import dns.namedict  --hidden-import   dns.tsigkeyring --hidden-import dns.update --hidden-import dns.version --hidden-import dns.zone -w`
生成的exe只有12.2MB，点击运行报错：
![1624937003(1)](https://user-images.githubusercontent.com/54022042/123732495-920a2b00-d8cc-11eb-93ef-b784f0b4e702.jpg)

师傅你打包好的可以正常运行的有48MB，请问是什么原因呢？

**Comment by qianxiao996** [comment]
请使用pyinstaller FrameScan-GUI.spec进行打包  那条命令是我以前打包的 现在应该缺少模块了。

**Comment by qianxiao996** [comment]
可以先去掉-w。看看报什么错误，解决后再打包就可以了。

**Comment by littlebin404** [comment]
直接用了项目中的FrameScan-GUI.spec，路径都改成一样的，还是报错了：
![1625035570(1)](https://user-images.githubusercontent.com/54022042/123914479-05d23380-d9b2-11eb-88c5-1fc7f6ecd4c9.jpg)

**Comment by qianxiao996** [comment]
路径需要改成你自己的，把-w去掉看看报什么错误













在 2021-06-30 14:47:11，"90後小斌" ***@***.***> 写道：

直接用了项目中的FrameScan-GUI.spec，路径都改成一样的，还是报错了：

**Comment by qianxiao996** [comment]
先保留控制台 看看报什么错误，再去解决就好了
